# Generated by Django 2.1.3 on 2019-06-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_incomeandexpense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incomeandexpense',
            options={'verbose_name_plural': 'Income and Expense'},
        ),
        migrations.AlterField(
            model_name='incomeandexpense',
            name='type',
            field=models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=255),
        ),
    ]
