# Generated by Django 2.1.3 on 2019-06-10 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190610_1521'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
