# Generated by Django 2.1.3 on 2019-09-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190610_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField()),
                ('date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('location', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='incomeandexpense',
            options={'ordering': ('date',), 'verbose_name_plural': 'Income and Expense'},
        ),
    ]
